### PR TITLE
Change

### PR DESCRIPTION
**Pull request by Bassprojekt**
Please wait with the merg. and wait for answer of the others

### CODE REVIEW

**Comment by lindi200000** [comment]
@Welenkens looks good :)

**Comment by der1sebi** [comment]
Plankenbau oder Bretterbau? What would be better in this case to stay the same in the translation?

**Comment by Welenkens** [comment]
It seems @der1sebi has some suggestion. Can I merge @lindi200000?

**Comment by der1sebi** [comment]
@Welenkens looking good now :)

**Comment by Bassprojekt** [comment]
@Welenkens Now you can merge it I think lindi has a lot to do at the moment.

**Pull request merged**
