### PR TITLE
a lot of cosmetics and shortens

### PR DESCRIPTION
**Pull request by michaelarlt**
Please let us use DC to discuss changes, since there are too many today

### CODE REVIEW

**Comment by michaelarlt** [comment]
@Welenkens please do not merge yet. Still in Discussion as of now
* Webstuhl <> Textilmaschine
* Apotherkertisch <> Pharmazeutischer Tisch

**Comment by michaelarlt** [comment]
Attached the screenshot-link, for the message he got
https://media.discordapp.net/attachments/1072837459886493756/1080174166831005766/eeee2.jpg

**Review by lindi200000 — APPROVED** [review]
@Welenkens you can merge :)

**Comment by michaelarlt** [comment]
@Welenkens i think we got all open questions discussed and solved. From my side i would release the PR now as there are none open questions. Feel free to get back to me in case of any question. Sorry for the inconvenience

**Pull request merged**
